"""empty message

Revision ID: 583f81c0b281
Revises: 0af6814fab38
Create Date: 2018-09-05 23:23:35.857985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583f81c0b281'
down_revision = '0af6814fab38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'last_seen')
    # ### end Alembic commands ###
