"""about me

Revision ID: 887557ec9d8e
Revises: 583f81c0b281
Create Date: 2018-09-06 00:04:30.855998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887557ec9d8e'
down_revision = '583f81c0b281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('about_me', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'about_me')
    # ### end Alembic commands ###
